# Generated by Django 2.2.5 on 2019-10-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twoDP3_app', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='twoDP3_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
